USE lab_mysql;
CREATE TABLE cars (id VARCHAR(15) PRIMARY KEY);
CREATE TABLE customers (id VARCHAR(15) PRIMARY KEY);
CREATE TABLE invoices (id VARCHAR(15) PRIMARY KEY);
CREATE TABLE salespersons (id VARCHAR(15) PRIMARY KEY);
ALTER TABLE cars ADD COLUMN vin VARCHAR(200);
ALTER TABLE cars ADD COLUMN manufacturer VARCHAR(200);
ALTER TABLE cars ADD COLUMN model  VARCHAR(200);
ALTER TABLE cars ADD COLUMN year DATE;
ALTER TABLE cars ADD COLUMN color TEXT;
ALTER TABLE customers ADD COLUMN name VARCHAR(200);
ALTER TABLE customers ADD COLUMN customerid VARCHAR(200);
ALTER TABLE customers ADD COLUMN phonenumber VARCHAR(200);
ALTER TABLE customers ADD COLUMN email VARCHAR(200);
ALTER TABLE customers ADD COLUMN address VARCHAR(200);
ALTER TABLE customers ADD COLUMN city VARCHAR(200);
ALTER TABLE customers ADD COLUMN state VARCHAR(200);
ALTER TABLE customers ADD COLUMN country VARCHAR(200);
ALTER TABLE customers ADD COLUMN zipcode VARCHAR(200);
ALTER TABLE salespersons ADD COLUMN name VARCHAR(200);
ALTER TABLE salespersons ADD COLUMN staffid VARCHAR(200);
ALTER TABLE salespersons ADD COLUMN store VARCHAR(200);
ALTER TABLE invoices ADD COLUMN invoicenumber VARCHAR(200);
ALTER TABLE invoices ADD COLUMN date DATE;
ALTER TABLE invoices ADD COLUMN carid INT;
ALTER TABLE invoices ADD COLUMN customerid INT;
ALTER TABLE invoices ADD COLUMN staffid INT;



